http:
  routers:
    outlook-mcp:
      rule: "Host(`omcp.ams.iosharp.com`)"
      entryPoints:
        - web-secure
      service: outlook-mcp
      tls:
        certResolver: myresolver

  services:
    outlook-mcp:
      loadBalancer:
        servers:
          - url: "http://192.168.178.42:3939"
